### ISSUE TITLE
ECONNRESET and EPIPE errors not handled due to removeAllListeners()

### ISSUE THREAD

**Issue by leeliu** [andris9/rai#1]
Using apple mail with simplesmtp, apple mail connects to test smtp user/pass (during testing, i just change the password by a few chars), it does a quick AUTH PLAIN check, then QUITs. Immediately following this, about 50% of the time, the connection somehow quits uncleanly and results in a crash of node with ECONNRESET or EPIPE.

I debugged it a bit and i think it's due to unhandled socket errors, since RAISocket _destroy() (rai.js:434) has removeAllListeners() which removes on("error") which i think is how net.js detects it as unhandled and crashes.

**Comment by tjunussov** [comment]
I am getting this error, when I use MacOS Mail APP

```
Connection closed
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at WriteWrap.afterWrite [as oncomplete] (net.js:779:14)
Emitted 'error' event at:
    at RAISocket._onError (/bms/smtp/node_modules/rai/lib/rai.js:450:10)
    at Socket.emit (events.js:189:13)
    at onwriteError (_stream_writable.js:431:12)
    at onwrite (_stream_writable.js:456:5)
    at _destroy (internal/streams/destroy.js:40:7)
    at Socket._destroy (net.js:604:3)
    at Socket.destroy (internal/streams/destroy.js:32:8)
    at WriteWrap.afterWrite [as oncomplete] (net.js:781:10)
```

tried workaround 
```
process.stdin.on('error', function () {
    console.error("Ignore EPIPE and ECONNRESET.");                                       
});
```
didnt help, my app exiting due to error
